In [38]:
import hepdata_lib

In [52]:
from hepdata_lib import Submission
submission1 = Submission()
submission1.read_abstract("abstract.txt")

In [5]:
#from hepdata_lib import Table
#table = Table("Figure 4b")
#table.description = "Distributions of \mllj for the data, and the post-fit backgrounds (stacked histograms), in the SRs of the \eeqq channel. The template for one signal hypothesis is shown overlaid as a yellow solid line. The overflow is included in the last bin. The middle panels show ratios of the data to the pre-fit background prediction and post-fit background yield as red open squares and blue points, respectively. The gray band in the middle panels indicates the systematic component of the post-fit uncertainty. The lower panels show the distributions of the pulls, defined in the text."
#table.location = "Data from Figure 4 (right)."
#table.keywords["observables"] = ["N"]
#table.add_image("QBH_CWR.pdf")

In [6]:
#submission1.add_table(table)

In [40]:
!head ADD_accEff_HEP.txt

3.0	0.48822 	0.48497 	0.49252
3.5	0.487208	0.486738	0.497874
4.0	0.48929	        0.487251	0.495648
4.5	0.487066	0.485303	0.491127
5.0	0.483149	0.481601	0.479999
5.5	0.479451	0.475679	0.470238
6.0	0.466667	0.462347	0.451808
6.5	0.452126	0.447362	0.428802
7.0	0.42611 	0.421757	0.399457
7.5	0.397014	0.396633	0.370678


In [53]:
# Figure for acceptance * efficiency
import numpy as np
from hepdata_lib import Variable, Uncertainty, Table
table = Table("Figure 4b")
table.description = "The product of acceptance and selection efficiency for QBH ADD and RS1 models, as a function of threshold mass of the signal."
table.location = "Data from Figure 4b"
table.add_image("QBH_CWR.pdf")

table.keywords["observables"] = ["Acceptance times efficiency"]
#fig5.keywords["reactions"] = ["P P --> W W j j", "P P --> W Z j j"]
#fig5.keywords["phrases"] = ["Same-sign WW", "WZ", "Georgi-Machacek", "Charged Higgs", "VBF"]

data4 = np.loadtxt("ADD_accEff_HEP.txt", skiprows=0)
dataRS1 = np.loadtxt("RS1_accEff_HEP.txt", skiprows=0)
print(dataRS1)

fig4_data = Variable("Threshold Mass", is_independent=True, is_binned=False, units="TeV")
fig4_data.values = [float(x) for x in data4[:,0]]

fig4_yields0 = Variable("Acceptance times efficiency for ADD signal 2018", is_independent=False, is_binned=False, units="")
#fig5_unc0 = Uncertainty("total uncertainty", is_symmetric=True)
fig4_yields0.values = [float(x) for x in data4[:,1]]
#fig5_unc0.values = [eval(x) for x in data5[:,3]]
#fig5_yields0.add_uncertainty(fig5_unc0)

fig4_yields1 = Variable("Acceptance times efficiency for ADD signal 2017", is_independent=False, is_binned=False, units="")
#fig5_unc1 = Uncertainty("total uncertainty", is_symmetric=True)
fig4_yields1.values = [float(x) for x in data4[:,2]]
#fig5_unc1.values = [eval(x) for x in data5[:,4]]
#fig5_yields1.add_uncertainty(fig5_unc1)

fig4_yields2 = Variable("Acceptance times efficiency for ADD signal 2016", is_independent=False, is_binned=False, units="")
#fig5_unc1 = Uncertainty("total uncertainty", is_symmetric=True)
fig4_yields2.values = [float(x) for x in data4[:,3]]
#fig5_unc1.values = [eval(x) for x in data5[:,4]]
#fig5_yields1.add_uncertainty(fig5_unc1)


fig4_rs1 = Variable("Threshold Mass", is_independent=True, is_binned=False, units="TeV")
fig4_rs1.values = [float(x) for x in dataRS1[:,0]]

fig4_yields3 = Variable("Acceptance times efficiency for RS1 signal 2018", is_independent=False, is_binned=False, units="")
fig4_yields3.values = [float(x) for x in dataRS1[:,1]]


fig4_yields4 = Variable("Acceptance times efficiency for RS1 signal 2017", is_independent=False, is_binned=False, units="")
fig4_yields4.values = [float(x) for x in dataRS1[:,2]]

fig4_yields5 = Variable("Acceptance times efficiency for RS1 signal 2016", is_independent=False, is_binned=False, units="")
fig4_yields5.values = [float(x) for x in dataRS1[:,3]]

table.add_variable(fig4_data)
table.add_variable(fig4_yields0)
table.add_variable(fig4_yields1)
table.add_variable(fig4_yields2)

#table.add_variable(fig4_rs1)
#table.add_variable(fig4_yields3)
#table.add_variable(fig4_yields4)
#table.add_variable(fig4_yields5)

submission1.add_table(table)

for table in submission1.tables:
    table.keywords["cmenergies"] = [13000]

[[3.       0.48758  0.48699  0.49616 ]
 [3.5      0.491316 0.49263  0.499306]
 [4.       0.489287 0.487498 0.495412]
 [4.5      0.487001 0.484474 0.487975]
 [5.       0.484405 0.479555 0.482029]
 [5.5      0.473992 0.472    0.449546]
 [6.       0.465694 0.464048 0.427142]
 [6.5      0.450781 0.445656 0.4162  ]
 [7.       0.424221 0.424221 0.389248]]


In [54]:
# Reading Figure of signal shapes 
import numpy as np
table = Table("Figure 3")
table.location = "Figure 3"
table.add_image("SignalShape_afterCWR.pdf")

In [55]:
from hepdata_lib import RootFileReader
reader = RootFileReader("Mass4TeV.root")
signal_qstar = reader.read_hist_1d("h_GJetInvtMass_VarBin_noMassCut")
#print(signal_qstar)
signal_qstar['x']= signal_qstar['x'][2:]
signal_qstar['x_edges']= signal_qstar['x_edges'][2:]
signal_qstar['x_labels']= signal_qstar['x_labels'][2:]
signal_qstar['y']= signal_qstar['y'][2:]
signal_qstar['dy']= signal_qstar['dy'][2:]
#signal_qstar

In [56]:
from hepdata_lib import Variable, Uncertainty

# x-axis:  Resonance mass with binning variable
mass = Variable("$m(gammaJ)$", is_independent=True, is_binned=True, units="GeV")
#mass.values = [ (0.4,0.6), (0.6,0.8), (0.8,1.0), (1.0,1.4), (1.4,2.0), (2.0,3.5), (3.5,10.0)]
mass.values = signal_qstar["x_edges"]

# y-axis: N events
sig = Variable("Number of expected signal events (pre-fit)", is_independent=False, is_binned=False, units="")
sig.values = signal_qstar["y"]
table.add_variable(mass)
table.add_variable(sig)
submission1.add_table(table)

In [57]:
#Reading Limits plots 
from hepdata_lib import Table
table = Table("Figure 5a")
table.description = "Exclusion limits on the product of cross section and branching fraction for the electron channel, as a function of the resonance mass hypothesis."

table.location = "Data from Figure 5a."
table.keywords["observables"] = ["SIG"]
table.keywords["reactions"] = ["P P --> N e --> e e  q q "]

table.add_image("Limits_f0p1_qstar.pdf")

In [58]:
import numpy as np
from hepdata_lib import RootFileReader
reader = RootFileReader("limits_freq_Qstar_f0p1_SigXBR_excitedquarks2016_CWR.root")
data = reader.read_graph("exp_Qstar_excitedquarks2016")
print(data)

defaultdict(<class 'list'>, {'x': [1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0, 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3.0, 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4.0, 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5.0, 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6.0, 6.1, 6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7.0], 'y': [0.016632601644604977, 0.012366750280590654, 0.009273670022040164, 0.0073082655049868175, 0.005882591250118293, 0.004917268004680685, 0.004057057909505953, 0.00341431963499175, 0.002844368848826537, 0.002322362330495404, 0.0020285685224543677, 0.0017216624541496678, 0.0014850688720824087, 0.0012812853325861468, 0.001115635119901498, 0.000980787349839206, 0.0008633055984153034, 0.0007627789287433704, 0.0006725187177404483, 0.0005970850784139891, 0.0005299393666129621, 0.0004757393852284013, 0.00043122104583783746, 0.0003899644479758776, 0.00035192804943371954, 0.0003146944159475594, 0.0002862124738460719, 0.00026089857714807013, 0.0002371513536865

In [59]:
import numpy as np
from hepdata_lib import RootFileReader
reader = RootFileReader("limits_freq_Qstar_f0p1_SigXBR_excitedquarks2016_CWR.root")
data_obs = reader.read_graph("obs_Qstar_excitedquarks2016")
print(data_obs)

defaultdict(<class 'list'>, {'x': [1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0, 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3.0, 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4.0, 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5.0, 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6.0, 6.1, 6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7.0], 'y': [0.028854945615109026, 0.007967232687739554, 0.003963483598670474, 0.007857961139452283, 0.007316458443126081, 0.0032879296252274533, 0.005437454324367107, 0.004580761236020942, 0.002321806266372121, 0.001748516569164908, 0.0024634546833283513, 0.0023505582925278995, 0.0017457805982221879, 0.001554679111408657, 0.0014752296315290983, 0.001763507388646194, 0.0009176512724771967, 0.0009359727406665767, 0.0006849937386571973, 0.0008042821214669908, 0.000909375909987266, 0.0009098662009439124, 0.0006467598070969058, 0.0003994518168276645, 0.00022802975558289276, 0.00015200620574388395, 0.00014340652341539485, 0.000135878540765718, 0.00012177390899562

In [60]:
from hepdata_lib import Variable
m = Variable("$m$", is_independent=True, is_binned=True, units="GeV")
m.values = data["x_edges"]
obs = Variable("Cross section upper limit at 95% CL", is_independent=False, is_binned=False, units="pb")
obs.values = data_obs["y_edges"]
obs.add_qualifier("Limit", "Observed")
obs.add_qualifier("SQRT(S)", 13, "TeV")
obs.add_qualifier("LUMINOSITY", 138, "fb$^{-1}$")
table.add_variable(m)
table.add_variable(obs)
submission1.add_table(table)

In [ ]:
from hepdata_lib import Variable, Uncertainty
import numpy as np
d = Variable("Heavy composite neutrino mass", is_independent=True, is_binned=False, units="GeV")
d.values = data[:,0]

obs = Variable("Cross section upper limit at 95% CL", is_independent=False, is_binned=False, units="pb")
obs.values = data[:,6]*[5.71E-03,2.82E-03,8.21E-04,1.43E-05,9.13E-08]
obs.add_qualifier("Limit", "Observed")
obs.add_qualifier("SQRT(S)", 13, "TeV")
obs.add_qualifier("LUMINOSITY", 138, "fb$^{-1}$")

exp = Variable("Cross section upper limit at 95% CL", is_independent=False, is_binned=False, units="pb")
exp.values = data[:,3]*[5.71E-03,2.82E-03,8.21E-04,1.43E-05,9.13E-08]
exp.add_qualifier("Limit", "Expected")
exp.add_qualifier("SQRT(S)", 13, "TeV")
exp.add_qualifier("LUMINOSITY", 138, "fb$^{-1}$")

# +/- 1 sigma
unc_1s = Uncertainty("1 s.d.", is_symmetric=False)
unc_1s.set_values_from_intervals(zip(data[:,2]*[5.71E-03,2.82E-03,8.21E-04,1.43E-05,9.13E-08], data[:,4]*[5.71E-03,2.82E-03,8.21E-04,1.43E-05,9.13E-08]), nominal=exp.values)
exp.add_uncertainty(unc_1s)

# +/- 2 sigma
unc_2s = Uncertainty("2 s.d.", is_symmetric=False)
unc_2s.set_values_from_intervals(zip(data[:,1]*[5.71E-03,2.82E-03,8.21E-04,1.43E-05,9.13E-08], data[:,5]*[5.71E-03,2.82E-03,8.21E-04,1.43E-05,9.13E-08]), nominal=exp.values)
exp.add_uncertainty(unc_2s)

In [61]:
outdir = "output"
submission1.create_files(outdir,remove_old=True)