In [2]:
import hepdata_lib

In [3]:
from hepdata_lib import Submission
submission1 = Submission()
submission1.read_abstract("abstract.txt")

In [5]:
#from hepdata_lib import Table
#table = Table("Figure 4b")
#table.description = "Distributions of \mllj for the data, and the post-fit backgrounds (stacked histograms), in the SRs of the \eeqq channel. The template for one signal hypothesis is shown overlaid as a yellow solid line. The overflow is included in the last bin. The middle panels show ratios of the data to the pre-fit background prediction and post-fit background yield as red open squares and blue points, respectively. The gray band in the middle panels indicates the systematic component of the post-fit uncertainty. The lower panels show the distributions of the pulls, defined in the text."
#table.location = "Data from Figure 4 (right)."
#table.keywords["observables"] = ["N"]
#table.add_image("QBH_CWR.pdf")

In [6]:
#submission1.add_table(table)

In [127]:
!head ADD_accEff_HEP.txt

3.0	0.48822 	0.48497 	0.49252
3.5	0.487208	0.486738	0.497874
4.0	0.48929	        0.487251	0.495648
4.5	0.487066	0.485303	0.491127
5.0	0.483149	0.481601	0.479999
5.5	0.479451	0.475679	0.470238
6.0	0.466667	0.462347	0.451808
6.5	0.452126	0.447362	0.428802
7.0	0.42611 	0.421757	0.399457
7.5	0.397014	0.396633	0.370678


In [4]:
# Figure for acceptance * efficiency
import numpy as np
from hepdata_lib import Variable, Uncertainty, Table
table = Table("Figure 4b")
table.description = "The product of acceptance and selection efficiency for QBH ADD and RS1 models, as a function of threshold mass of the signal."
table.location = "Data from Figure 4b"
#table.add_image("QBH_CWR.pdf")

table.keywords["observables"] = ["Acceptance times efficiency"]
#fig5.keywords["reactions"] = ["P P --> W W j j", "P P --> W Z j j"]
#fig5.keywords["phrases"] = ["Same-sign WW", "WZ", "Georgi-Machacek", "Charged Higgs", "VBF"]

data4 = np.loadtxt("ADD_accEff_HEP.txt", skiprows=0)
dataRS1 = np.loadtxt("RS1_accEff_HEP.txt", skiprows=0)
print(dataRS1)

fig4_data = Variable("Threshold Mass", is_independent=True, is_binned=False, units="TeV")
fig4_data.values = [float(x) for x in data4[:,0]]

fig4_yields0 = Variable("Acceptance times efficiency for ADD signal 2018", is_independent=False, is_binned=False, units="")
#fig5_unc0 = Uncertainty("total uncertainty", is_symmetric=True)
fig4_yields0.values = [float(x) for x in data4[:,1]]
#fig5_unc0.values = [eval(x) for x in data5[:,3]]
#fig5_yields0.add_uncertainty(fig5_unc0)

fig4_yields1 = Variable("Acceptance times efficiency for ADD signal 2017", is_independent=False, is_binned=False, units="")
#fig5_unc1 = Uncertainty("total uncertainty", is_symmetric=True)
fig4_yields1.values = [float(x) for x in data4[:,2]]
#fig5_unc1.values = [eval(x) for x in data5[:,4]]
#fig5_yields1.add_uncertainty(fig5_unc1)

fig4_yields2 = Variable("Acceptance times efficiency for ADD signal 2016", is_independent=False, is_binned=False, units="")
#fig5_unc1 = Uncertainty("total uncertainty", is_symmetric=True)
fig4_yields2.values = [float(x) for x in data4[:,3]]
#fig5_unc1.values = [eval(x) for x in data5[:,4]]
#fig5_yields1.add_uncertainty(fig5_unc1)

table.add_variable(fig4_data)
table.add_variable(fig4_yields0)
table.add_variable(fig4_yields1)
table.add_variable(fig4_yields2)

submission1.add_table(table)

table = Table("Figure 4b for RS1")
table.description = "The product of acceptance and selection efficiency for QBH RS1 models, as a function of threshold mass of the signal."
table.location = "Data from Figure 4b for RS1 signal"

fig4_rs1 = Variable("Threshold Mass", is_independent=True, is_binned=False, units="TeV")
fig4_rs1.values = [float(x) for x in dataRS1[:,0]]

fig4_yields3 = Variable("Acceptance times efficiency for RS1 signal 2018", is_independent=False, is_binned=False, units="")
fig4_yields3.values = [float(x) for x in dataRS1[:,1]]


fig4_yields4 = Variable("Acceptance times efficiency for RS1 signal 2017", is_independent=False, is_binned=False, units="")
fig4_yields4.values = [float(x) for x in dataRS1[:,2]]

fig4_yields5 = Variable("Acceptance times efficiency for RS1 signal 2016", is_independent=False, is_binned=False, units="")
fig4_yields5.values = [float(x) for x in dataRS1[:,3]]


table.add_variable(fig4_rs1)
table.add_variable(fig4_yields3)
table.add_variable(fig4_yields4)
table.add_variable(fig4_yields5)

submission1.add_table(table)

for table in submission1.tables:
    table.keywords["cmenergies"] = [13000]

[[3.       0.48758  0.48699  0.49616 ]
 [3.5      0.491316 0.49263  0.499306]
 [4.       0.489287 0.487498 0.495412]
 [4.5      0.487001 0.484474 0.487975]
 [5.       0.484405 0.479555 0.482029]
 [5.5      0.473992 0.472    0.449546]
 [6.       0.465694 0.464048 0.427142]
 [6.5      0.450781 0.445656 0.4162  ]
 [7.       0.424221 0.424221 0.389248]]


In [5]:
# Reading Figure of signal shapes 
import numpy as np
table = Table("Figure 3")
table.location = "Figure 3"
table.add_image("SignalShape_afterCWR.pdf")

In [6]:
from hepdata_lib import RootFileReader
reader = RootFileReader("Mass4TeV.root")
signal_qstar = reader.read_hist_1d("h_GJetInvtMass_VarBin_noMassCut")
#print(signal_qstar)
signal_qstar['x']= signal_qstar['x'][2:]
signal_qstar['x_edges']= signal_qstar['x_edges'][2:]
signal_qstar['x_labels']= signal_qstar['x_labels'][2:]
signal_qstar['y']= signal_qstar['y'][2:]
signal_qstar['dy']= signal_qstar['dy'][2:]
#signal_qstar

In [7]:
from hepdata_lib import Variable, Uncertainty

# x-axis:  Resonance mass with binning variable
mass = Variable("$m(gammaJ)$", is_independent=True, is_binned=True, units="GeV")
#mass.values = [ (0.4,0.6), (0.6,0.8), (0.8,1.0), (1.0,1.4), (1.4,2.0), (2.0,3.5), (3.5,10.0)]
mass.values = signal_qstar["x_edges"]

# y-axis: N events
sig = Variable("Number of expected signal events (pre-fit)", is_independent=False, is_binned=False, units="")
sig.values = signal_qstar["y"]
table.add_variable(mass)
table.add_variable(sig)
submission1.add_table(table)

In [8]:
# Fitting plots for q* 
from hepdata_lib import Table, Uncertainty
table = Table("Figure 5")
table.description = "Fitting distribution of data with expected q*, and QBH signal events"
table.location = "Data from Figure 5"
table.keywords["observables"] = ["m(photon+jet)"]
import numpy as np
from hepdata_lib import RootFileReader
reader1 = RootFileReader("TotalData_JetPt170_Mass760_RunII_unblind.root")
reader2 = RootFileReader("Mass2TeV_qstar_RunII.root")
#reader3 = RootFileReader("Mass3000GeV_ADD_RunII.root")
data_qstar = reader1.read_hist_1d("h_GJetInvtMass_VarBin_noMassCut")
sig_qstar = reader2.read_hist_1d("h_GJetInvtMass_VarBin_noMassCut")

mjj                     = Variable("$M_{JJ}$", is_independent=True, is_binned=True, units="GeV")
mjj.values              = data_qstar["x_edges"]  #[12:80]


data                = Variable("Number of data events", is_independent=False, is_binned=False, units="")
sig1                = Variable("Number of q* signal events", is_independent=False, is_binned=False, units="")
data.values = data_qstar["y"]
sig1.values = sig_qstar["y"]
#data['dy']= data_qstar['dy'][2:]
print(data_qstar["dy"])
unc_data            = Uncertainty("Error", is_symmetric=True)
#unc_data.set_values_from_intervals(data["dy"],nominal=data.values) #data_qstar["dy"]
unc_data.values = data_qstar["dy"]

data.add_uncertainty(unc_data)
table.add_variable(data)
table.add_variable(sig1)
table.add_variable(mjj)
submission1.add_table(table)

[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.4142135623730951, 3.7416573867739413, 6.164414002968976, 9.38083151964686, 12.649110640673518, 15.165750888103101, 20.73644135332772, 29.715315916207253, 57.148928248918196, 139.37718608151047, 235.55678720852006, 327.7087121209932, 402.0248748522907, 439.8204178980326, 445.4435991233907, 429.9441824237188, 404.54665985520137, 372.40569275992544, 342.95480751842507, 307.8376195334157, 284.98947348981153, 253.69666927257836, 228.8536650351049, 208.15859338494772, 186.3249849054066, 170.2410056361275, 152.17095649301808, 137.90213921473443, 123.84667940643382, 111.13955191559843, 99.90495483208028, 90.89004345911603, 82.79492738084863, 73.89181280764467, 65.97726881282674, 58.84725991921799, 53.637673327615545, 48.373546489791295, 43.069710934716056, 38.3275357934736, 33.85262175962151, 30.789608636681304, 27.694764848252458, 24.758836806279895, 21.863211109075447, 20.174241001832016, 16.492422502470642, 16.703293088490067, 1

In [9]:
# Fitting plots for b* 
from hepdata_lib import Table, Uncertainty
table = Table("Figure 6a")
table.description = "Fitting distribution of data with expected b* events"
table.location = "Data from Figure 6a"
table.keywords["observables"] = ["m(photon+jet)"]
import numpy as np
from hepdata_lib import RootFileReader
reader1 = RootFileReader("TotalData_JetPt170_Mass760_RunII_Masshisto.root")
reader2 = RootFileReader("Mass1TeV_bstar_RunII.root")
reader3 = RootFileReader("Mass2TeV_bstar_RunII.root")


data_bstar = reader1.read_hist_1d("h_GJet_VarBin_1BTag_MassCut")
sig_bstar_1btag_1tev = reader2.read_hist_1d("h_GbJetInvtMass_VarBin_1BTag_MassCut")
sig_bstar_1btag_2tev = reader3.read_hist_1d("h_GbJetInvtMass_VarBin_1BTag_MassCut")


mjj                     = Variable("$M_{JJ}$", is_independent=True, is_binned=True, units="GeV")
mjj.values              = data_qstar["x_edges"]

data                = Variable("Number of data events", is_independent=False, is_binned=False, units="")
sig1                = Variable("Number of b* 1btag signal events for mass 1Tev", is_independent=False, is_binned=False, units="")
sig2                = Variable("Number of b* 1btag signal events for mass 2Tev", is_independent=False, is_binned=False, units="")   

data.values = data_bstar["y"]  #[12:80]
sig1.values = sig_bstar_1btag_1tev["y"] 
sig2.values = sig_bstar_1btag_1tev["y"]

#[12:80]
#data['dy']= data_qstar['dy'][2:]
print(data_bstar["dy"])
unc_data            = Uncertainty("Error", is_symmetric=True)
#unc_data.set_values_from_intervals(data["dy"],nominal=data.values) #data_qstar["dy"]
unc_data.values = data_bstar["dy"]   #[12:80]

data.add_uncertainty(unc_data)
table.add_variable(data)
table.add_variable(sig1)
table.add_variable(sig2)
submission1.add_table(table)

[1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 84.38601779915912, 75.39893898457723, 69.36137253543934, 63.592452382338585, 58.58327406350724, 54.644304369257, 48.72371086031933, 44.51965857910413, 40.44749683231337, 38.144462245521304, 32.817678162843876, 29.949958263743873, 28.495613697550013, 25.475478405713993, 23.643180835073778, 20.639767440550294, 20.37154878746336, 17.944358444926362, 16.673332000533065, 14.071247279470288, 12.922847983320086, 12.206555615733702, 10.816653826391969, 10.04987562112089, 8.94427190999916, 7.681145747868608, 7.0710678118654755, 7.0, 5.5677643628300215, 6.082762530298219, 4.242640687119285, 4.358898943540674, 3.872983346207417, 3.1622776601683795, 1.4142135623730951, 2.8284271247461903, 1.0, 1.7320508075688772, 1.4142135623730951, 1.4142135623730951, 1.0, 1.0, 1.4142135623730951, 1.0, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.0, 1.8, 1.8

In [10]:
# Fitting plots for b* 0btag 
from hepdata_lib import Table, Uncertainty
table = Table("Figure 6b")
table.description = "Fitting distribution of data with expected b* events for 0btag category"
table.location = "Data from Figure 6b"
table.keywords["observables"] = ["m(photon+jet)"]
import numpy as np
from hepdata_lib import RootFileReader
reader1 = RootFileReader("TotalData_JetPt170_Mass760_RunII_Masshisto.root")
reader2 = RootFileReader("Mass1TeV_bstar_RunII.root")
reader3 = RootFileReader("Mass2TeV_bstar_RunII.root")


data_bstar = reader1.read_hist_1d("h_GJet_VarBin_0BTag_MassCut")
sig_bstar_1btag_1tev = reader2.read_hist_1d("h_GbJetInvtMass_VarBin_0BTag_MassCut")
sig_bstar_1btag_2tev = reader3.read_hist_1d("h_GbJetInvtMass_VarBin_0BTag_MassCut")


mjj                     = Variable("$M_{JJ}$", is_independent=True, is_binned=True, units="GeV")
mjj.values              = data_qstar["x_edges"]

data                = Variable("Number of data events", is_independent=False, is_binned=False, units="")
sig1                = Variable("Number of b* 0btag signal events for mass 1Tev", is_independent=False, is_binned=False, units="")
sig2                = Variable("Number of b* 0btag signal events for mass 2Tev", is_independent=False, is_binned=False, units="")   

data.values = data_bstar["y"]  #[12:80]
sig1.values = sig_bstar_1btag_1tev["y"] 
sig2.values = sig_bstar_1btag_1tev["y"]

#[12:80]
#data['dy']= data_qstar['dy'][2:]
print(data_bstar["dy"])
unc_data            = Uncertainty("Error", is_symmetric=True)
#unc_data.set_values_from_intervals(data["dy"],nominal=data.values) #data_qstar["dy"]
unc_data.values = data_bstar["dy"]   #[12:80]

data.add_uncertainty(unc_data)
table.add_variable(data)
table.add_variable(sig1)
table.add_variable(sig2)
submission1.add_table(table)

[1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 272.20947815974375, 242.23335856153255, 218.08943119738746, 198.20696254168269, 176.87566254292872, 161.2327510154187, 144.1596337398233, 130.51819796488152, 117.05554237198682, 104.38869670610895, 94.36100889668359, 85.81375181169973, 77.73673520286275, 69.36137253543934, 61.59545437773797, 55.10898293381942, 49.61854492022111, 44.9221548904324, 39.71145930332956, 35.651086939951774, 31.28897569432403, 28.26658805020514, 25.495097567963924, 22.627416997969522, 19.949937343260004, 18.65475810617763, 14.89966442575134, 15.165750888103101, 11.313708498984761, 11.224972160321824, 9.055385138137417, 8.54400374531753, 7.745966692414834, 7.211102550927978, 6.557438524302, 4.47213595499958, 3.7416573867739413, 3.3166247903554, 2.8284271247461903, 1.7320508075688772, 2.6457513110645907, 1.7320508075688772, 1.0, 1.8, 1.7320508075688772,

In [35]:
#Reading Limits plots 
from hepdata_lib import Table
table = Table("Figure 7c")
table.description = "Exclusion limits on the product of cross section and branching fraction for the electron channel, as a function of the resonance mass hypothesis."

table.location = "Data from Figure 7c."
table.keywords["observables"] = ["SIG"]
table.keywords["reactions"] = ["P P --> N e --> e e  q q "]

table.add_image("Limits_f0p1_qstar.pdf")

import numpy as np
from hepdata_lib import RootFileReader, Uncertainty
reader = RootFileReader("limits_freq_Qstar_f0p1_SigXBR_excitedquarks2016_CWR.root")
exp_qstar_f0p1 = reader.read_graph("exp_Qstar_excitedquarks2016")
obs_qstar_f0p1 = reader.read_graph("obs_Qstar_excitedquarks2016")
unc_1s_qstar_f0p1 = reader.read_graph("exp1sigma_Qstar_excitedquarks2016")
unc_2s_qstar_f0p1 = reader.read_graph("exp2sigma_Qstar_excitedquarks2016")

m = Variable("$m$", is_independent=True, is_binned=False, units="GeV")
m.values = obs_qstar_f0p1["x"]


exp_qstar_f0p1_coup = Variable("Cross section upper limit at 95% CL", is_independent=False, is_binned=False, units="pb")
exp_qstar_f0p1_coup.add_qualifier("Limit", "Expected")
exp_qstar_f0p1_coup.add_qualifier("SQRT(S)", 13, "TeV")
exp_qstar_f0p1_coup.add_qualifier("LUMINOSITY", 138, "fb$^{-1}$")

obs_qstar_f0p1_coup = Variable("Cross section upper limit at 95% CL", is_independent=False, is_binned=False, units="pb")
obs_qstar_f0p1_coup.add_qualifier("Limit", "Expected")
obs_qstar_f0p1_coup.add_qualifier("SQRT(S)", 13, "TeV")
obs_qstar_f0p1_coup.add_qualifier("LUMINOSITY", 138, "fb$^{-1}$")

obs_qstar_f0p1_coup.values = obs_qstar_f0p1["y"]
exp_qstar_f0p1_coup.values = exp_qstar_f0p1["y"]

unc_1s_qstar_f0p1_coup = Uncertainty("1 s.d.", is_symmetric=False)
unc_1s_qstar_f0p1_coup.set_values_from_intervals(unc_1s_qstar_f0p1["dy"],nominal=exp.values)
exp_qstar_f0p1_coup.add_uncertainty(unc_1s_qstar_f0p1_coup)

unc_2s_qstar_f0p1_coup = Uncertainty("2 s.d.", is_symmetric=False)
unc_2s_qstar_f0p1_coup.set_values_from_intervals(unc_2s_qstar_f0p1["dy"],nominal=exp.values)
exp_qstar_f0p1_coup.add_uncertainty(unc_2s_qstar_f0p1_coup)

table.add_variable(m)
table.add_variable(obs_qstar_f0p1_coup)
table.add_variable(exp_qstar_f0p1_coup)
submission1.add_table(table)

print(unc_1s_qstar_f0p1["dy"])

#from __future__ import print_function
#print(unc_1s_graph)

[(-0.00459239097973381, 0.006563528065608966), (-0.0034810734560481375, 0.004781556709153393), (-0.0025496366844059842, 0.0036595596071891407), (-0.0020571781601447193, 0.00288397541809257), (-0.0016173176202533821, 0.0023213776316229374), (-0.0013841446154227747, 0.0019208432165410795), (-0.0011347331172320407, 0.0016009889710848274), (-0.0009651745714973377, 0.0013473527743146545), (-0.0008074654714318929, 0.001099764341788753), (-0.000603305364921615, 0.0008979323443824103), (-0.0005710146832269736, 0.0007196504580742504), (-0.0004856361535176284, 0.0006931247198270332), (-0.0004233633016287227, 0.0005860353214786076), (-0.0003637340042898704, 0.0005158331258211184), (-0.00031267437155534864, 0.00045803788341183983), (-0.000278428033831838, 0.0003948555385381662), (-0.0002471452024027819, 0.000350999655147258), (-0.00021836666714358016, 0.000313168337084218), (-0.0001925271438286067, 0.0002761108922916743), (-0.00017236258019981464, 0.0002451407060631624), (-0.0001529793905832116, 0

In [13]:
outdir = "output"
submission1.create_files(outdir,remove_old=True)