In [31]:
import hepdata_lib

In [17]:
from hepdata_lib import Submission
submission1 = Submission()
submission1.read_abstract("abstract.txt")

In [30]:
from hepdata_lib import Table
table = Table("Figure 4a")
table.description = "Distributions of \mllj for the data, and the post-fit backgrounds (stacked histograms), in the SRs of the \eeqq channel. The template for one signal hypothesis is shown overlaid as a yellow solid line. The overflow is included in the last bin. The middle panels show ratios of the data to the pre-fit background prediction and post-fit background yield as red open squares and blue points, respectively. The gray band in the middle panels indicates the systematic component of the post-fit uncertainty. The lower panels show the distributions of the pulls, defined in the text."
table.location = "Data from Figure 4 (upper left)."
table.keywords["observables"] = ["N"]
table.add_image("QBH_CWR.pdf")

In [19]:
submission1.add_table(table)

In [20]:
!head ADD_accEff_HEP.txt

3.0	0.48822 	0.48497 	0.49252
3.5	0.487208	0.486738	0.497874
4.0	0.48929	        0.487251	0.495648
4.5	0.487066	0.485303	0.491127
5.0	0.483149	0.481601	0.479999
5.5	0.479451	0.475679	0.470238
6.0	0.466667	0.462347	0.451808
6.5	0.452126	0.447362	0.428802
7.0	0.42611 	0.421757	0.399457
7.5	0.397014	0.396633	0.370678


In [21]:
# Figure for acceptance * efficiency
import numpy as np
from hepdata_lib import Variable, Uncertainty
fig5 = Table("Figure 5")
fig5.description = "The product of acceptance and selection efficiency for QBH ADD and RS1 models, as a function of threshold mass of the signal."
fig5.location = "Data from Figure 5"

fig5.keywords["observables"] = ["Acceptance times efficiency"]
#fig5.keywords["reactions"] = ["P P --> W W j j", "P P --> W Z j j"]
#fig5.keywords["phrases"] = ["Same-sign WW", "WZ", "Georgi-Machacek", "Charged Higgs", "VBF"]

data5 = np.loadtxt("ADD_accEff_HEP.txt", skiprows=0)
dataRS1 = np.loadtxt("RS1_accEff_HEP.txt", skiprows=0)
print(dataRS1)

fig5_data = Variable("Threshold Mass", is_independent=True, is_binned=False, units="TeV")
fig5_data.values = [float(x) for x in data5[:,0]]

fig5_yields0 = Variable("Acceptance times efficiency for ADD signal 2018", is_independent=False, is_binned=False, units="")
#fig5_unc0 = Uncertainty("total uncertainty", is_symmetric=True)
fig5_yields0.values = [float(x) for x in data5[:,1]]
#fig5_unc0.values = [eval(x) for x in data5[:,3]]
#fig5_yields0.add_uncertainty(fig5_unc0)

fig5_yields1 = Variable("Acceptance times efficiency for ADD signal 2017", is_independent=False, is_binned=False, units="")
#fig5_unc1 = Uncertainty("total uncertainty", is_symmetric=True)
fig5_yields1.values = [float(x) for x in data5[:,2]]
#fig5_unc1.values = [eval(x) for x in data5[:,4]]
#fig5_yields1.add_uncertainty(fig5_unc1)

fig5_yields2 = Variable("Acceptance times efficiency for ADD signal 2016", is_independent=False, is_binned=False, units="")
#fig5_unc1 = Uncertainty("total uncertainty", is_symmetric=True)
fig5_yields2.values = [float(x) for x in data5[:,3]]
#fig5_unc1.values = [eval(x) for x in data5[:,4]]
#fig5_yields1.add_uncertainty(fig5_unc1)


fig5_rs1 = Variable("Threshold Mass", is_independent=True, is_binned=False, units="TeV")
fig5_rs1.values = [float(x) for x in dataRS1[:,0]]

fig5_yields3 = Variable("Acceptance times efficiency for ADD signal 2018", is_independent=False, is_binned=False, units="")
fig5_yields3.values = [float(x) for x in dataRS1[:,1]]


fig5_yields4 = Variable("Acceptance times efficiency for ADD signal 2017", is_independent=False, is_binned=False, units="")
fig5_yields4.values = [float(x) for x in dataRS1[:,2]]

fig5_yields5 = Variable("Acceptance times efficiency for ADD signal 2016", is_independent=False, is_binned=False, units="")
fig5_yields5.values = [float(x) for x in dataRS1[:,3]]

fig5.add_variable(fig5_data)
fig5.add_variable(fig5_yields0)
fig5.add_variable(fig5_yields1)
fig5.add_variable(fig5_yields2)

fig5.add_variable(fig5_rs1)
fig5.add_variable(fig5_yields3)
fig5.add_variable(fig5_yields4)
fig5.add_variable(fig5_yields5)

submission1.add_table(fig5)

for fig5 in submission.tables:
    fig5.keywords["cmenergies"] = [13000]

[[3.       0.48758  0.48699  0.49616 ]
 [3.5      0.491316 0.49263  0.499306]
 [4.       0.489287 0.487498 0.495412]
 [4.5      0.487001 0.484474 0.487975]
 [5.       0.484405 0.479555 0.482029]
 [5.5      0.473992 0.472    0.449546]
 [6.       0.465694 0.464048 0.427142]
 [6.5      0.450781 0.445656 0.4162  ]
 [7.       0.424221 0.424221 0.389248]]


In [22]:
# Reading Figure of signal shapes 
import numpy as np
from hepdata_lib import RootFileReader
reader = RootFileReader("Mass4TeV.root")
signal_qstar = reader.read_hist_1d("h_GJetInvtMass_VarBin_noMassCut")
#print(signal_qstar)
signal_qstar['x']= signal_qstar['x'][2:]
signal_qstar['x_edges']= signal_qstar['x_edges'][2:]
signal_qstar['x_labels']= signal_qstar['x_labels'][2:]
signal_qstar['y']= signal_qstar['y'][2:]
signal_qstar['dy']= signal_qstar['dy'][2:]
signal_qstar

{'x': [36.5,
  51.5,
  66.5,
  82.0,
  98.5,
  115.5,
  133.0,
  151.0,
  169.5,
  189.0,
  209.0,
  229.5,
  251.0,
  273.0,
  295.5,
  319.0,
  343.5,
  368.5,
  394.0,
  420.5,
  448.0,
  476.5,
  506.0,
  536.5,
  568.0,
  600.5,
  634.0,
  668.5,
  704.5,
  742.0,
  780.5,
  820.0,
  860.5,
  902.5,
  946.0,
  991.0,
  1037.5,
  1085.5,
  1135.5,
  1187.0,
  1240.0,
  1295.0,
  1352.0,
  1411.0,
  1472.0,
  1535.0,
  1600.0,
  1667.0,
  1736.5,
  1808.5,
  1883.0,
  1960.0,
  2039.5,
  2122.0,
  2207.5,
  2296.0,
  2387.5,
  2482.0,
  2579.5,
  2680.5,
  2785.0,
  2893.0,
  3004.5,
  3119.5,
  3238.5,
  3362.0,
  3490.0,
  3622.0,
  3758.5,
  3900.0,
  4046.5,
  4198.0,
  4354.5,
  4516.0,
  4683.0,
  4856.0,
  5035.0,
  5220.0,
  5411.5,
  5609.5,
  5814.0,
  6025.5,
  6244.5,
  6471.0,
  6705.0,
  6947.0,
  7197.5,
  7456.5,
  7724.0,
  8001.0,
  8287.5,
  8583.5,
  8890.0,
  9207.0,
  9534.5,
  9873.5,
  10224.5,
  10587.5,
  10962.5,
  11350.0,
  11751.0,
  12166.0,
  12595.0,

In [23]:
from hepdata_lib import Variable, Uncertainty

# x-axis:  Resonance mass with binning variable
mass = Variable("$m(gammaJ)$", is_independent=True, is_binned=True, units="GeV")
#mass.values = [ (0.4,0.6), (0.6,0.8), (0.8,1.0), (1.0,1.4), (1.4,2.0), (2.0,3.5), (3.5,10.0)]
mass.values = signal_qstar["x_edges"]

# y-axis: N events
sig = Variable("Number of expected signal events (pre-fit)", is_independent=False, is_binned=False, units="")
sig.values = signal_qstar["y"]
table.add_variable(mass)
table.add_variable(sig)
submission1.add_table(table)

In [24]:
#Reading Limits plots 
from hepdata_lib import Table
table = Table("Figure 5a")
table.description = "Exclusion limits on the product of cross section and branching fraction for the electron channel, as a function of the resonance mass hypothesis."

table.location = "Data from Figure 5a."
table.keywords["observables"] = ["SIG"]
table.keywords["reactions"] = ["P P --> N e --> e e  q q "]

table.add_image("Limits_f0p1_qstar.pdf")

In [25]:
import numpy as np
from hepdata_lib import RootFileReader
reader = RootFileReader("limits_freq_Qstar_f0p1_SigXBR_excitedquarks2016_CWR.root")
data = reader.read_graph("exp_Qstar_excitedquarks2016")
print(data)

defaultdict(<class 'list'>, {'x': [1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0, 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3.0, 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4.0, 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5.0, 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6.0, 6.1, 6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7.0], 'y': [0.016632601644604977, 0.012366750280590654, 0.009273670022040164, 0.0073082655049868175, 0.005882591250118293, 0.004917268004680685, 0.004057057909505953, 0.00341431963499175, 0.002844368848826537, 0.002322362330495404, 0.0020285685224543677, 0.0017216624541496678, 0.0014850688720824087, 0.0012812853325861468, 0.001115635119901498, 0.000980787349839206, 0.0008633055984153034, 0.0007627789287433704, 0.0006725187177404483, 0.0005970850784139891, 0.0005299393666129621, 0.0004757393852284013, 0.00043122104583783746, 0.0003899644479758776, 0.00035192804943371954, 0.0003146944159475594, 0.0002862124738460719, 0.00026089857714807013, 0.0002371513536865

In [26]:
import numpy as np
from hepdata_lib import RootFileReader
reader = RootFileReader("limits_freq_Qstar_f0p1_SigXBR_excitedquarks2016_CWR.root")
data_obs = reader.read_graph("obs_Qstar_excitedquarks2016")
print(data_obs)

defaultdict(<class 'list'>, {'x': [1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0, 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3.0, 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4.0, 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5.0, 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6.0, 6.1, 6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7.0], 'y': [0.028854945615109026, 0.007967232687739554, 0.003963483598670474, 0.007857961139452283, 0.007316458443126081, 0.0032879296252274533, 0.005437454324367107, 0.004580761236020942, 0.002321806266372121, 0.001748516569164908, 0.0024634546833283513, 0.0023505582925278995, 0.0017457805982221879, 0.001554679111408657, 0.0014752296315290983, 0.001763507388646194, 0.0009176512724771967, 0.0009359727406665767, 0.0006849937386571973, 0.0008042821214669908, 0.000909375909987266, 0.0009098662009439124, 0.0006467598070969058, 0.0003994518168276645, 0.00022802975558289276, 0.00015200620574388395, 0.00014340652341539485, 0.000135878540765718, 0.00012177390899562

In [27]:
from hepdata_lib import Variable
m = Variable("$m$", is_independent=True, is_binned=True, units="GeV")
m.values = data["x_edges"]
obs = Variable("Cross section upper limit at 95% CL", is_independent=False, is_binned=False, units="pb")
obs.values = data_obs["y_edges"]
obs.add_qualifier("Limit", "Observed")
obs.add_qualifier("SQRT(S)", 13, "TeV")
obs.add_qualifier("LUMINOSITY", 138, "fb$^{-1}$")
table.add_variable(m)
table.add_variable(obs)
submission1.add_table(table)

In [ ]:
from hepdata_lib import Variable, Uncertainty
import numpy as np
d = Variable("Heavy composite neutrino mass", is_independent=True, is_binned=False, units="GeV")
d.values = data[:,0]

obs = Variable("Cross section upper limit at 95% CL", is_independent=False, is_binned=False, units="pb")
obs.values = data[:,6]*[5.71E-03,2.82E-03,8.21E-04,1.43E-05,9.13E-08]
obs.add_qualifier("Limit", "Observed")
obs.add_qualifier("SQRT(S)", 13, "TeV")
obs.add_qualifier("LUMINOSITY", 138, "fb$^{-1}$")

exp = Variable("Cross section upper limit at 95% CL", is_independent=False, is_binned=False, units="pb")
exp.values = data[:,3]*[5.71E-03,2.82E-03,8.21E-04,1.43E-05,9.13E-08]
exp.add_qualifier("Limit", "Expected")
exp.add_qualifier("SQRT(S)", 13, "TeV")
exp.add_qualifier("LUMINOSITY", 138, "fb$^{-1}$")

# +/- 1 sigma
unc_1s = Uncertainty("1 s.d.", is_symmetric=False)
unc_1s.set_values_from_intervals(zip(data[:,2]*[5.71E-03,2.82E-03,8.21E-04,1.43E-05,9.13E-08], data[:,4]*[5.71E-03,2.82E-03,8.21E-04,1.43E-05,9.13E-08]), nominal=exp.values)
exp.add_uncertainty(unc_1s)

# +/- 2 sigma
unc_2s = Uncertainty("2 s.d.", is_symmetric=False)
unc_2s.set_values_from_intervals(zip(data[:,1]*[5.71E-03,2.82E-03,8.21E-04,1.43E-05,9.13E-08], data[:,5]*[5.71E-03,2.82E-03,8.21E-04,1.43E-05,9.13E-08]), nominal=exp.values)
exp.add_uncertainty(unc_2s)

In [29]:
outdir = "output"
submission1.create_files(outdir,remove_old=True)

Full-size PNG file output/QBH_CWR.png is newer than its source file.                        Remove the thumbnail file or use create_files(remove_old=True)                           to force recreation.
Thumbnail PNG file output/thumb_QBH_CWR.png is newer than its source file.                        Remove the thumbnail file or use create_files(remove_old=True)                           to force recreation.
	 error - submission.yaml is invalid HEPData YAML.
	 error - Duplicate table name: Figure 4a
	 error - Duplicate table data_file: figure_4a.yaml


AssertionError: The tar ball is not valid